import pathlib


def _relative_to(
    path: str,
    base_path: pathlib.Path,
    cache: dict[str, str] | None = None,
) -> str:
    if path.startswith("<") and path.endswith(">"):
        # There are many cases where an entry could be generated by the plugin, and
        # the file name could be something like `<auto_accounts>`. To avoid the error
        # of calling relative path logic with an invalid path, we are returning the
        # plugin special filename as is
        return path

    if cache is not None:
        cached = cache.get(path)
        if cached is not None:
            return cached

    result = _strip_prefix(path, str(base_path))
    if cache is not None:
        cache[path] = result
    return result


def _strip_prefix(path: str, base: str) -> str:
    base = base.rstrip("/")
    if path == base or path == base + "/":
        return "."
    prefix = base + "/"
    if path.startswith(prefix):
        return path[len(prefix) :]
    # Match pathlib.Path.relative_to: non-relative paths raise ValueError.
    # Paths that escape via ".." after the base prefix (e.g. /base/../other)
    # still strip the prefix and keep the ".." segments, same as pathlib.
    raise ValueError(
        f"{path!r} is not in the subpath of {base!r} OR one path is relative and "
        f"the other is absolute."
    )


def strip_base_path(
    paths: str | list[str],
    base_path: pathlib.Path,
    cache: dict[str, str] | None = None,
) -> str | list[str]:
    """Strip the base path off the given path

    :param paths: the path to strip off, could be a list of path or just one path
    :param base_path: the base path
    :param cache: optional path -> stripped path cache for repeated lookups
    :return: path with base path stripped
    """
    if isinstance(paths, list):
        return [_relative_to(path, base_path, cache=cache) for path in paths]
    return _relative_to(paths, base_path, cache=cache)
